In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Data.csv to Data.csv

In [ ]:
import io
threeDayData = pd.read_csv(io.BytesIO(uploaded['Data.csv']))
# Dataset is now stored in a Pandas Dataframe

In [ ]:
threeDayData.head()

              Time  Occupancy    co2  humidity  pm25    VOC
0  11/28/2022 9:30          0  428.7      35.1   0.0  135.7
1  11/28/2022 9:35          0  426.3      34.8   0.0  142.8
2  11/28/2022 9:40          0  432.1      34.8   0.0  148.1
3  11/28/2022 9:45          1  439.5      34.7   0.2  151.4
4  11/28/2022 9:50          1  450.0      34.7   0.8  162.8

In [ ]:
train3day = pd.DataFrame({'occupancy': threeDayData["Occupancy"],
                      'co2': threeDayData['co2'],
                    'pm25': threeDayData['pm25'],
                     'humidity':threeDayData['humidity'],
                      'voc': threeDayData['VOC']})

In [ ]:
train3day

     occupancy    co2  pm25  humidity    voc
0            0  428.7   0.0      35.1  135.7
1            0  426.3   0.0      34.8  142.8
2            0  432.1   0.0      34.8  148.1
3            1  439.5   0.2      34.7  151.4
4            1  450.0   0.8      34.7  162.8
..         ...    ...   ...       ...    ...
510          6  741.4   0.5      20.3  230.9
511          5  729.1   0.5      20.1  277.2
512          3  697.3   0.5      19.5  238.4
513          3  658.2   0.2      19.1  213.5
514          3  616.4   0.2      18.9  190.0

[515 rows x 5 columns]

In [ ]:
y = train3day['occupancy']

X = train3day.copy(deep=True)
X.drop('occupancy', inplace=True, axis=1)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X

       co2  pm25  humidity    voc
0    428.7   0.0      35.1  135.7
1    426.3   0.0      34.8  142.8
2    432.1   0.0      34.8  148.1
3    439.5   0.2      34.7  151.4
4    450.0   0.8      34.7  162.8
..     ...   ...       ...    ...
510  741.4   0.5      20.3  230.9
511  729.1   0.5      20.1  277.2
512  697.3   0.5      19.5  238.4
513  658.2   0.2      19.1  213.5
514  616.4   0.2      18.9  190.0

[515 rows x 4 columns]

In [ ]:
#train the RF classifier
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=500, n_jobs=1, oob_score=True, random_state=True,
                       verbose=0, warm_start=True)

clf.predict(X_test)

array([ 6,  0,  4,  3, 11,  1,  3,  0,  1,  0,  0,  1,  0,  4,  0,  5,  0,
       10,  0,  7,  5, 11,  1,  0,  4,  3, 11,  2,  1,  2,  0, 11, 18,  1,
        6,  2,  4,  4, 10,  0, 10, 10,  0,  5,  4,  6,  2, 11,  5,  0,  1,
        0, 11,  0,  0,  0,  0, 10,  0, 10,  1,  0,  0,  1,  3,  1,  2,  1,
        0,  4,  1, 11,  6,  2,  0,  5,  3,  0,  2,  0,  0, 11,  0,  1,  7,
        3,  0,  2,  4,  3,  4,  0,  1,  9,  0,  2,  0,  2,  6,  4,  2,  0,
       11])

In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_test)
acc =  accuracy_score(np.array(y_test),prediction)
print ('The accuracy of Random Forest is {} on data within the test set'.format(acc))

In [ ]:
train3day

In [ ]:

import pandas as pd

import numpy as np
 
importances = clf.feature_importances_
#
# Sort the feature importance in descending order
#
sorted_indices = np.argsort(importances)[::-1]
 
feat_labels = train3day.columns[1:]
 
for f in range(X_train.shape[1]):
    print("%2d) %-*s %f" % (f + 1, 30,
                            feat_labels[sorted_indices[f]],
                            importances[sorted_indices[f]])) 

import matplotlib.pyplot as plt
 
plt.title('Feature Importance')
plt.bar(range(X_train.shape[1]), importances[sorted_indices], align='center')
plt.xticks(range(X_train.shape[1]), X_train.columns[sorted_indices], rotation=90)
plt.tight_layout()
plt.show()

In [ ]:
## use a different day of data and make that X_test --> run again without refitting the model
##import .csv that is just Tuesday 11/22 and wasn't a part of the modeling

from google.colab import files
uploaded = files.upload()

Saving 11_22.csv to 11_22.csv

In [ ]:
import io
df11_22 = pd.read_csv(io.BytesIO(uploaded['11_22.csv']))
# Dataset is now stored in a Pandas Dataframe

In [ ]:
df11_22

In [ ]:
train11_22 = pd.DataFrame({'occupancy': df11_22["Occupancy"],
                      'co2': df11_22['co2'],
                    'pm25': df11_22['pm25'],
                     'humidity':df11_22['humidity'],
                      'voc': df11_22['VOC']})

In [ ]:
train11_22

In [ ]:

y2 = train11_22['occupancy']

X2 = train11_22.copy(deep=True)
X2.drop('occupancy', inplace=True, axis=1)


X_train2,X_test2,y_train2,y_test2 = train_test_split(X2,y2,test_size=0.2,random_state=1)

In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_test2)
acc =  accuracy_score(np.array(y_test2),prediction)
print ('The accuracy of Random Forest is {} for 11/22 from model of 11/28-11/30'.format(acc))

Same process, just with only CO2 - retrain the data to create a model from just c02 then check with 11_22 data

In [ ]:
##remake model using the full 3 day data set
train3 = pd.DataFrame({'occupancy': threeDayData["Occupancy"],
                      'co2': threeDayData['co2']})

In [ ]:
train3

In [1]:
y = train3['occupancy']

X = train3.copy(deep=True)
X.drop('occupancy', inplace=True, axis=1)


X_train3,X_test3,y_train3,y_test3 = train_test_split(X,y,test_size=0.2,random_state=1)

NameError: ignored

In [ ]:
#retrain the RF classifier using only c02
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train3,y_train3)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=500, n_jobs=1, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

clf.predict(X_test3)

In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_test3)
acc =  accuracy_score(np.array(y_test3),prediction)
print ('The accuracy of Random Forest is {} on data within the training set'.format(acc))

use a different day of data and make that X_test --> run again without refitting the model
import .csv that is just Tuesday 11/22 and wasn't a part of the modeling

In [ ]:
df11_22

In [ ]:
trainCO2 = pd.DataFrame({'occupancy': df11_22["Occupancy"],
                      'co2': df11_22['co2']})

In [ ]:
trainCO2

    occupancy    co2
0           0  470.1
1           1  467.1
2           3  466.9
3           7  466.3
4           7  462.4
..        ...    ...
83          0  419.1
84          0  417.7
85          0  418.8
86          0  417.2
87          0  418.9

[88 rows x 2 columns]

In [ ]:
yCO2 = trainCO2['occupancy']

XCO2 = trainCO2.copy(deep=True)
XCO2.drop('occupancy', inplace=True, axis=1)


X_trainCO2,X_testCO2,y_trainCO2,y_testCO2 = train_test_split(XCO2,yCO2,test_size=0.2,random_state=1)

In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_testCO2)
acc =  accuracy_score(np.array(y_testCO2),prediction)
print ('The accuracy of Random Forest is {} for 11/22 from model of 11/28-11/30 JUST CO2'.format(acc))

Same process, just with only HUMIDITY - retrain the data to create a model from just HUNMIDITY then check with 11_22 data

In [ ]:
##remake model using the full 3 day data set
train4 = pd.DataFrame({'occupancy': threeDayData["Occupancy"],
                      'humidity': threeDayData['humidity']})

In [ ]:
train4

     occupancy  humidity
0            0      34.9
1            0      35.4
2            0      35.7
3            0      36.1
4            0      36.5
..         ...       ...
388          3      40.9
389          3      39.9
390          3      39.2
391          3      38.9
392          3      38.6

[393 rows x 2 columns]

In [ ]:
y = train4['occupancy']

X = train4
X_train4,X_test4,y_train4,y_test4 = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
#retrain the RF classifier using only c02
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train4,y_train4)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=6, max_features='auto', max_leaf_nodes=None,
                       min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=500, n_jobs=1, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

clf.predict(X_test4)

use a different day of data and make that X_test --> run again without refitting the model
import .csv that is just Tuesday 11/22 and wasn't a part of the modeling

In [ ]:
df11_22

                Time  Occupancy    co2  pm25  humidity    VOC
0   11/22/2022 10:45          0  470.1   0.1      19.0  130.0
1   11/22/2022 10:50          1  467.1   0.2      18.9  125.0
2   11/22/2022 10:55          3  466.9   0.7      18.9  138.0
3   11/22/2022 11:00          7  466.3   0.6      20.3  171.0
4   11/22/2022 11:05          7  462.4   0.6      20.7  176.0
..               ...        ...    ...   ...       ...    ...
83  11/22/2022 17:40          0  419.1   0.0      15.5   94.0
84  11/22/2022 17:45          0  417.7   0.0      15.5   98.4
85  11/22/2022 17:50          0  418.8   0.0      15.6   96.7
86  11/22/2022 17:55          0  417.2   0.0      15.5   99.7
87  11/22/2022 18:00          0  418.9   0.0      15.5   96.5

[88 rows x 6 columns]

In [ ]:
trainHUM = pd.DataFrame({'occupancy': df11_22["Occupancy"],
                      'humidity': df11_22['humidity']})
testHUM = pd.DataFrame()

In [ ]:
trainHUM

    occupancy  humidity
0           0      19.0
1           1      18.9
2           3      18.9
3           7      20.3
4           7      20.7
..        ...       ...
83          0      15.5
84          0      15.5
85          0      15.6
86          0      15.5
87          0      15.5

[88 rows x 2 columns]

In [ ]:
yHUM = trainHUM['occupancy']

XHUM = trainHUM
X_trainHUM,X_testHUM,y_trainHUM,y_testHUM = train_test_split(XHUM,yHUM,test_size=0.2,random_state=1)

In [ ]:
#make prediction and check model's accuracy
prediction = clf.predict(X_testHUM)
acc =  accuracy_score(np.array(y_testHUM),prediction)
print ('The accuracy of Random Forest is {} for 11/22 from model of 11/28-11/30 JUST HUM'.format(acc))